# Generated by Django 4.2.19 on 2025-03-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='tags',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('exercise', 'Exercise'), ('outdoor', 'Outdoor'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100),
        ),
    ]
