# Generated by Django 4.2.19 on 2025-04-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='isbn',
            field=models.CharField(blank=True, help_text='Auto-generated ISBN-13', max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(default='UVA Recreation Center', max_length=100),
        ),
    ]
