# Generated by Django 4.2.19 on 2025-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_equipment_isbn_equipment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='isbn',
            field=models.CharField(blank=True, help_text='Auto-generated ISBN-13', max_length=13, unique=True),
        ),
    ]
