# Generated by Django 4.2.19 on 2025-03-30 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='rented_at',
            new_name='rented_on',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='returned_at',
            new_name='returned_on',
        ),
        migrations.AddField(
            model_name='rental',
            name='return_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipment'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
