# Generated by Django 4.2.19 on 2025-03-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_collection_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
