# Generated by Django 4.2.19 on 2025-03-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_collection_creator_collection_description'),
        ('app', '0003_rename_rented_at_rental_rented_on_and_more'),
    ]

    operations = [
    ]
