# Generated by Django 4.2.19 on 2025-03-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, default='equipment_images/placeholder.jpg', null=True, upload_to='equipment/'),
        ),
    ]
