# Generated by Django 4.2.19 on 2025-04-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_rating_rating'),
        ('app', '0004_notification'),
    ]

    operations = [
    ]
