# Generated by Django 4.2.19 on 2025-04-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rating'),
        ('app', '0007_rename_requested_on_rentalrequest_created_at'),
    ]

    operations = [
    ]
